[Pull Request] Struct optimized, code optimized.
Crequency/KitX-Mobile pull request #33
Opened 2023-07-07 09:34 UTC by Dynesshely

## What does this PR do?

Features:

- Updated dependencies.

Refactorings:

- Use one dart file to export other dart files on same level.
- Use more extension methods.
- Apart some data and info to alone dart files.
- Apart some ui code to alone widgets in alone dart files.

## Related issues

None.

2023-07-07 11:05 UTC, LYF511 commented on kitx_mobile/lib/utils/handlers/task_handler.dart
Is this a 'handler'?
I think it's better to put this in /lib/utils/delay.dart

2023-07-07 11:09 UTC, LYF511 commented on kitx_mobile/lib/pages/pages.dart
> +    ];
Strange Indentation

2023-07-07 11:25 UTC, LYF511 requested changes
I think it's better to refactor `int_ext.dart` and `theme_mode_ext.dart` to one file like enmus/theme_mode.dart or directly themes/convert.dart.
Because these two files are about theme mod, but not whole int class.
It's not necessary to expand whole int class.

2023-07-09 10:52 UTC, Dynesshely commented on kitx_mobile/lib/pages/pages.dart
> +    ];
Auto indentated by flutter itself.

2023-07-09 10:53 UTC, Dynesshely commented on kitx_mobile/lib/utils/handlers/task_handler.dart
I am going to upgrade it to a task system, after that, the `delay` method will be deprecated.

2023-07-09 10:54 UTC, Dynesshely commented
> I think it's better to refactor `int_ext.dart` and `theme_mode_ext.dart` to one file like enmus/theme_mode.dart or directly themes/convert.dart. Because these two files are about theme mod, but not whole int class. It's not necessary to expand whole int class.

You're right, I am going to think another way to achieve an elegant converting way.

2023-07-09 16:07 UTC, Dynesshely commented
> > I think it's better to refactor `int_ext.dart` and `theme_mode_ext.dart` to one file like enmus/theme_mode.dart or directly themes/convert.dart. Because these two files are about theme mod, but not whole int class. It's not necessary to expand whole int class.
> 
> You're right, I am going to think another way to achieve an elegant converting way.

I didn't think of a better way, since the `int` and `ThemeMode` classes are not part of what we can modify, except for adding extension methods for them, I can't think of other codes that can elegantly implement the conversion between `int` and `ThemeMode`.

2023-07-09 16:09 UTC, Dynesshely commented on kitx_mobile/lib/utils/handlers/task_handler.dart
In commit d4b447b, I convert delay function to alone class. This might solved problem.

2023-07-10 01:16 UTC, Sadinary approved these changes
Well done.

2023-07-10 01:16 UTC, merged